VenariPetFoodDB = {
  version = "tbc-anniversary-cn",
  foodTypes = { "Bread", "Cheese", "Fish", "Fruit", "Fungus", "Meat" },

  localizedFoodTypeNames = {
    enUS = {
      Bread = "Bread",
      Cheese = "Cheese",
      Fish = "Fish",
      Fruit = "Fruit",
      Fungus = "Fungus",
      Meat = "Meat",
    },
    zhCN = {
      Bread = "面包",
      Cheese = "奶酪",
      Fish = "鱼",
      Fruit = "水果",
      Fungus = "蘑菇",
      Meat = "肉",
    },
  },

  foodTypeAliases = {
    Meat = { "meat", "raw meat", "肉", "生肉", "肉类", "肉類" },
    Fish = { "fish", "raw fish", "鱼", "魚", "生鱼", "生魚", "鱼类", "魚類" },
    Fruit = { "fruit", "水果" },
    Bread = { "bread", "面包", "麵包" },
    Fungus = { "fungus", "mushroom", "蘑菇" },
    Cheese = { "cheese", "奶酪", "乳酪", "起司" },
  },

  foodConsumableSubTypes = {
    ["food & drink"] = true,
    ["food"] = true,
    ["食物和饮料"] = true,
    ["食物和飲料"] = true,
    ["食物"] = true,
  },

  petFamilies = {
    Bat = { "Fruit", "Fungus" },
    Bear = { "Bread", "Cheese", "Fish", "Fruit", "Fungus", "Meat" },
    Boar = { "Bread", "Cheese", "Fish", "Fruit", "Fungus", "Meat" },
    ["Carrion Bird"] = { "Fish", "Meat" },
    Cat = { "Fish", "Meat" },
    Crab = { "Bread", "Fish" },
    Crocolisk = { "Fish", "Meat" },
    Dragonhawk = { "Meat", "Fish", "Fruit" },
    Gorilla = { "Fruit", "Fungus" },
    Hyena = { "Fruit", "Meat" },
    ["Nether Ray"] = { "Meat" },
    Owl = { "Meat" },
    Raptor = { "Meat" },
    Ravager = { "Meat" },
    Scorpid = { "Meat" },
    Serpent = { "Meat", "Fish" },
    Spider = { "Meat" },
    Sporebat = { "Fungus", "Fruit", "Bread", "Cheese" },
    Tallstrider = { "Cheese", "Fruit", "Fungus" },
    Turtle = { "Fruit", "Fungus" },
    ["Warp Stalker"] = { "Fruit", "Fish" },
    ["Wind Serpent"] = { "Bread", "Cheese", "Fish" },
    Wolf = { "Meat" },
  },

  localizedFamilyNames = {
    enUS = {
      Bat = "Bat",
      Bear = "Bear",
      Boar = "Boar",
      ["Carrion Bird"] = "Carrion Bird",
      Cat = "Cat",
      Crab = "Crab",
      Crocolisk = "Crocolisk",
      Dragonhawk = "Dragonhawk",
      Gorilla = "Gorilla",
      Hyena = "Hyena",
      ["Nether Ray"] = "Nether Ray",
      Owl = "Owl",
      Raptor = "Raptor",
      Ravager = "Ravager",
      Scorpid = "Scorpid",
      Serpent = "Serpent",
      Spider = "Spider",
      Sporebat = "Sporebat",
      Tallstrider = "Tallstrider",
      Turtle = "Turtle",
      ["Warp Stalker"] = "Warp Stalker",
      ["Wind Serpent"] = "Wind Serpent",
      Wolf = "Wolf",
    },
    zhCN = {
      Bat = "蝙蝠",
      Bear = "熊",
      Boar = "野猪",
      ["Carrion Bird"] = "食腐鸟",
      Cat = "猫",
      Crab = "螃蟹",
      Crocolisk = "鳄鱼",
      Dragonhawk = "龙鹰",
      Gorilla = "猩猩",
      Hyena = "土狼",
      ["Nether Ray"] = "虚空鳐",
      Owl = "猫头鹰",
      Raptor = "迅猛龙",
      Ravager = "掠食者",
      Scorpid = "蝎子",
      Serpent = "蛇",
      Spider = "蜘蛛",
      Sporebat = "孢子蝠",
      Tallstrider = "陆行鸟",
      Turtle = "海龟",
      ["Warp Stalker"] = "迁跃捕猎者",
      ["Wind Serpent"] = "风蛇",
      Wolf = "狼",
    },
  },

  petFamilyAliases = {
    ["Bat"] = "Bat",
    ["Bear"] = "Bear",
    ["Boar"] = "Boar",
    ["Carrion Bird"] = "Carrion Bird",
    ["Cat"] = "Cat",
    ["Crab"] = "Crab",
    ["Crocolisk"] = "Crocolisk",
    ["Dragonhawk"] = "Dragonhawk",
    ["Gorilla"] = "Gorilla",
    ["Hyena"] = "Hyena",
    ["Nether Ray"] = "Nether Ray",
    ["Owl"] = "Owl",
    ["Raptor"] = "Raptor",
    ["Ravager"] = "Ravager",
    ["Scorpid"] = "Scorpid",
    ["Serpent"] = "Serpent",
    ["Spider"] = "Spider",
    ["Sporebat"] = "Sporebat",
    ["Tallstrider"] = "Tallstrider",
    ["Turtle"] = "Turtle",
    ["Warp Stalker"] = "Warp Stalker",
    ["Wind Serpent"] = "Wind Serpent",
    ["Wolf"] = "Wolf",
    ["蝙蝠"] = "Bat",
    ["熊"] = "Bear",
    ["野猪"] = "Boar",
    ["野豬"] = "Boar",
    ["食腐鸟"] = "Carrion Bird",
    ["食腐鳥"] = "Carrion Bird",
    ["腐肉鸟"] = "Carrion Bird",
    ["腐肉鳥"] = "Carrion Bird",
    ["猫"] = "Cat",
    ["貓"] = "Cat",
    ["螃蟹"] = "Crab",
    ["鳄鱼"] = "Crocolisk",
    ["鱷魚"] = "Crocolisk",
    ["龙鹰"] = "Dragonhawk",
    ["龍鷹"] = "Dragonhawk",
    ["猩猩"] = "Gorilla",
    ["土狼"] = "Hyena",
    ["虚空鳐"] = "Nether Ray",
    ["虛空鰩"] = "Nether Ray",
    ["猫头鹰"] = "Owl",
    ["貓頭鷹"] = "Owl",
    ["迅猛龙"] = "Raptor",
    ["迅猛龍"] = "Raptor",
    ["掠食者"] = "Ravager",
    ["蝎子"] = "Scorpid",
    ["蠍子"] = "Scorpid",
    ["蛇"] = "Serpent",
    ["蜘蛛"] = "Spider",
    ["孢子蝠"] = "Sporebat",
    ["陆行鸟"] = "Tallstrider",
    ["陸行鳥"] = "Tallstrider",
    ["海龟"] = "Turtle",
    ["海龜"] = "Turtle",
    ["迁跃捕猎者"] = "Warp Stalker",
    ["遷躍捕獵者"] = "Warp Stalker",
    ["风蛇"] = "Wind Serpent",
    ["風蛇"] = "Wind Serpent",
    ["狼"] = "Wolf",
  },

  petIcons = {
    ["132182"] = "Bat",
    ["132183"] = "Bear",
    ["132184"] = "Boar",
    ["132185"] = "Cat",
    ["132186"] = "Crab",
    ["132187"] = "Crocolisk",
    ["132188"] = "Dragonhawk",
    ["132189"] = "Gorilla",
    ["132190"] = "Hyena",
    ["132191"] = "Nether Ray",
    ["132192"] = "Owl",
    ["132193"] = "Raptor",
    ["132194"] = "Ravager",
    ["132195"] = "Scorpid",
    ["132196"] = "Spider",
    ["132197"] = "Sporebat",
    ["132198"] = "Tallstrider",
    ["132199"] = "Turtle",
    ["132200"] = "Carrion Bird",
    ["132201"] = "Warp Stalker",
    ["132202"] = "Wind Serpent",
    ["132203"] = "Wolf",
    ["136040"] = "Serpent",
  },

  foodItems = {
    [4540] = { type = "Bread", itemLevel = 5, requiredLevel = 6, foodLevel = 5, classId = 0, subClassId = 5, flags = { vendor = true, prepared = true } },
    [4541] = { type = "Bread", itemLevel = 15, requiredLevel = 5, foodLevel = 15, classId = 0, subClassId = 5, flags = { vendor = true, prepared = true } },
    [4542] = { type = "Bread", itemLevel = 25, requiredLevel = 15, foodLevel = 25, classId = 0, subClassId = 5, flags = { vendor = true, prepared = true } },
    [4544] = { type = "Bread", itemLevel = 35, requiredLevel = 25, foodLevel = 35, classId = 0, subClassId = 5, flags = { vendor = true, prepared = true } },
    [4601] = { type = "Bread", itemLevel = 45, requiredLevel = 35, foodLevel = 45, classId = 0, subClassId = 5, flags = { vendor = true, prepared = true } },
    [8950] = { type = "Bread", itemLevel = 55, requiredLevel = 45, foodLevel = 55, classId = 0, subClassId = 5, flags = { vendor = true, prepared = true } },
    [1113] = { type = "Bread", itemLevel = 15, requiredLevel = 5, foodLevel = 15, classId = 0, subClassId = 5, flags = { conjured = true, prepared = true } },
    [5349] = { type = "Bread", itemLevel = 5, requiredLevel = 1, foodLevel = 5, classId = 0, subClassId = 5, flags = { conjured = true, prepared = true } },
    [1114] = { type = "Bread", itemLevel = 25, requiredLevel = 15, foodLevel = 25, classId = 0, subClassId = 5, flags = { conjured = true, prepared = true } },
    [1487] = { type = "Bread", itemLevel = 35, requiredLevel = 25, foodLevel = 35, classId = 0, subClassId = 5, flags = { conjured = true, prepared = true } },
    [8075] = { type = "Bread", itemLevel = 45, requiredLevel = 35, foodLevel = 45, classId = 0, subClassId = 5, flags = { conjured = true, prepared = true } },
    [8076] = { type = "Bread", itemLevel = 55, requiredLevel = 45, foodLevel = 55, classId = 0, subClassId = 5, flags = { conjured = true, prepared = true } },
    [22895] = { type = "Bread", itemLevel = 65, requiredLevel = 55, foodLevel = 65, classId = 0, subClassId = 5, flags = { conjured = true, prepared = true } },
    [22019] = { type = "Bread", itemLevel = 75, requiredLevel = 65, foodLevel = 75, classId = 0, subClassId = 5, flags = { conjured = true, prepared = true } },
    [28486] = { type = "Bread", itemLevel = 65, requiredLevel = 55, foodLevel = 65, classId = 0, subClassId = 5, flags = { conjured = true, prepared = true } },
    [29449] = { type = "Bread", itemLevel = 75, requiredLevel = 65, foodLevel = 75, classId = 0, subClassId = 5, flags = { vendor = true, tbc = true, prepared = true } },
    [27855] = { type = "Bread", itemLevel = 65, requiredLevel = 55, foodLevel = 65, classId = 0, subClassId = 5, flags = { vendor = true, tbc = true, prepared = true } },

    [2070] = { type = "Cheese", itemLevel = 5, requiredLevel = 1, foodLevel = 5, classId = 0, subClassId = 5, flags = { vendor = true, prepared = true } },
    [414] = { type = "Cheese", itemLevel = 15, requiredLevel = 5, foodLevel = 15, classId = 0, subClassId = 5, flags = { vendor = true, prepared = true } },
    [422] = { type = "Cheese", itemLevel = 25, requiredLevel = 15, foodLevel = 25, classId = 0, subClassId = 5, flags = { vendor = true, prepared = true } },
    [1707] = { type = "Cheese", itemLevel = 35, requiredLevel = 25, foodLevel = 35, classId = 0, subClassId = 5, flags = { vendor = true, prepared = true } },
    [3927] = { type = "Cheese", itemLevel = 45, requiredLevel = 35, foodLevel = 45, classId = 0, subClassId = 5, flags = { vendor = true, prepared = true } },
    [8932] = { type = "Cheese", itemLevel = 55, requiredLevel = 45, foodLevel = 55, classId = 0, subClassId = 5, flags = { vendor = true, prepared = true } },
    [27857] = { type = "Cheese", itemLevel = 65, requiredLevel = 55, foodLevel = 65, classId = 0, subClassId = 5, flags = { vendor = true, tbc = true, prepared = true } },
    [29448] = { type = "Cheese", itemLevel = 75, requiredLevel = 65, foodLevel = 75, classId = 0, subClassId = 5, flags = { vendor = true, tbc = true, prepared = true } },

    [4592] = { type = "Fish", itemLevel = 15, requiredLevel = 5, foodLevel = 15, classId = 0, subClassId = 5, flags = { vendor = true, cooked = true, prepared = true } },
    [4593] = { type = "Fish", itemLevel = 25, requiredLevel = 15, foodLevel = 25, classId = 0, subClassId = 5, flags = { vendor = true, cooked = true, prepared = true } },
    [4594] = { type = "Fish", itemLevel = 35, requiredLevel = 25, foodLevel = 35, classId = 0, subClassId = 5, flags = { vendor = true, cooked = true, prepared = true } },
    [787] = { type = "Fish", itemLevel = 5, requiredLevel = 1, foodLevel = 5, classId = 0, subClassId = 5, flags = { vendor = true, cooked = true, prepared = true } },
    [8957] = { type = "Fish", itemLevel = 55, requiredLevel = 45, foodLevel = 55, classId = 0, subClassId = 5, flags = { vendor = true, cooked = true, prepared = true } },
    [21552] = { type = "Fish", itemLevel = 45, requiredLevel = 35, foodLevel = 45, classId = 0, subClassId = 5, flags = { vendor = true, cooked = true, prepared = true } },
    [29452] = { type = "Fish", itemLevel = 75, requiredLevel = 65, foodLevel = 75, classId = 0, subClassId = 5, flags = { vendor = true, cooked = true, tbc = true, prepared = true } },
    [27858] = { type = "Fish", itemLevel = 65, requiredLevel = 55, foodLevel = 65, classId = 0, subClassId = 5, flags = { vendor = true, cooked = true, tbc = true, prepared = true } },
    [7974] = { type = "Fish", itemLevel = 45, requiredLevel = 0, foodLevel = 45, classId = 7, subClassId = 8, flags = { raw = true, cookable = true, petRaw = true } },
    [4655] = { type = "Fish", itemLevel = 35, requiredLevel = 0, foodLevel = 35, classId = 7, subClassId = 8, flags = { raw = true, cookable = true, petRaw = true } },
    [5504] = { type = "Fish", itemLevel = 23, requiredLevel = 0, foodLevel = 23, classId = 7, subClassId = 8, flags = { raw = true, cookable = true, petRaw = true } },
    [21071] = { type = "Fish", itemLevel = 20, requiredLevel = 10, foodLevel = 20, classId = 7, subClassId = 8, flags = { raw = true, cookable = true, petRaw = true } },
    [6362] = { type = "Fish", itemLevel = 35, requiredLevel = 25, foodLevel = 35, classId = 7, subClassId = 8, flags = { raw = true, cookable = true, petRaw = true } },
    [13759] = { type = "Fish", itemLevel = 45, requiredLevel = 35, foodLevel = 45, classId = 7, subClassId = 8, flags = { raw = true, cookable = true, petRaw = true } },
    [6291] = { type = "Fish", itemLevel = 5, requiredLevel = 1, foodLevel = 5, classId = 7, subClassId = 8, flags = { raw = true, cookable = true, petRaw = true } },
    [8365] = { type = "Fish", itemLevel = 35, requiredLevel = 25, foodLevel = 35, classId = 7, subClassId = 8, flags = { raw = true, cookable = true, petRaw = true } },
    [6308] = { type = "Fish", itemLevel = 25, requiredLevel = 15, foodLevel = 25, classId = 7, subClassId = 8, flags = { raw = true, cookable = true, petRaw = true } },
    [4603] = { type = "Fish", itemLevel = 45, requiredLevel = 35, foodLevel = 45, classId = 7, subClassId = 8, flags = { raw = true, cookable = true, petRaw = true } },
    [13754] = { type = "Fish", itemLevel = 45, requiredLevel = 35, foodLevel = 45, classId = 7, subClassId = 8, flags = { raw = true, cookable = true, petRaw = true } },
    [13760] = { type = "Fish", itemLevel = 45, requiredLevel = 35, foodLevel = 45, classId = 7, subClassId = 8, flags = { raw = true, cookable = true, petRaw = true } },
    [13758] = { type = "Fish", itemLevel = 45, requiredLevel = 35, foodLevel = 45, classId = 7, subClassId = 8, flags = { raw = true, cookable = true, petRaw = true } },
    [6361] = { type = "Fish", itemLevel = 15, requiredLevel = 5, foodLevel = 15, classId = 7, subClassId = 8, flags = { raw = true, cookable = true, petRaw = true } },
    [6289] = { type = "Fish", itemLevel = 15, requiredLevel = 5, foodLevel = 15, classId = 7, subClassId = 8, flags = { raw = true, cookable = true, petRaw = true } },
    [13756] = { type = "Fish", itemLevel = 45, requiredLevel = 35, foodLevel = 45, classId = 7, subClassId = 8, flags = { raw = true, cookable = true, petRaw = true } },
    [13889] = { type = "Fish", itemLevel = 55, requiredLevel = 45, foodLevel = 55, classId = 7, subClassId = 8, flags = { raw = true, cookable = true, petRaw = true } },
    [6303] = { type = "Fish", itemLevel = 5, requiredLevel = 1, foodLevel = 5, classId = 7, subClassId = 8, flags = { raw = true, cookable = true, petRaw = true } },
    [6317] = { type = "Fish", itemLevel = 15, requiredLevel = 5, foodLevel = 15, classId = 7, subClassId = 8, flags = { raw = true, cookable = true, petRaw = true } },
    [8959] = { type = "Fish", itemLevel = 55, requiredLevel = 45, foodLevel = 55, classId = 7, subClassId = 8, flags = { raw = true, cookable = true, petRaw = true } },
    [27662] = { type = "Fish", itemLevel = 65, requiredLevel = 55, foodLevel = 65, classId = 0, subClassId = 5, flags = { tbc = true, cooked = true, prepared = true } },
    [27663] = { type = "Fish", itemLevel = 65, requiredLevel = 55, foodLevel = 65, classId = 0, subClassId = 5, flags = { tbc = true, cooked = true, prepared = true } },
    [27664] = { type = "Fish", itemLevel = 65, requiredLevel = 55, foodLevel = 65, classId = 0, subClassId = 5, flags = { tbc = true, cooked = true, prepared = true } },
    [27665] = { type = "Fish", itemLevel = 65, requiredLevel = 55, foodLevel = 65, classId = 0, subClassId = 5, flags = { tbc = true, cooked = true, prepared = true } },
    [27666] = { type = "Fish", itemLevel = 65, requiredLevel = 55, foodLevel = 65, classId = 0, subClassId = 5, flags = { tbc = true, cooked = true, prepared = true } },
    [27667] = { type = "Fish", itemLevel = 65, requiredLevel = 55, foodLevel = 65, classId = 0, subClassId = 5, flags = { tbc = true, cooked = true, prepared = true } },
    [33052] = { type = "Fish", itemLevel = 70, requiredLevel = 65, foodLevel = 70, classId = 0, subClassId = 5, flags = { tbc = true, cooked = true, prepared = true } },
    [6290] = { type = "Fish", itemLevel = 5, requiredLevel = 1, foodLevel = 5, classId = 0, subClassId = 5, flags = { cooked = true, prepared = true } },
    [8364] = { type = "Fish", itemLevel = 35, requiredLevel = 25, foodLevel = 35, classId = 0, subClassId = 5, flags = { cooked = true, prepared = true } },
    [6887] = { type = "Fish", itemLevel = 45, requiredLevel = 35, foodLevel = 45, classId = 0, subClassId = 5, flags = { cooked = true, prepared = true } },
    [13927] = { type = "Fish", itemLevel = 45, requiredLevel = 35, foodLevel = 45, classId = 0, subClassId = 5, flags = { cooked = true, prepared = true } },
    [13932] = { type = "Fish", itemLevel = 45, requiredLevel = 35, foodLevel = 45, classId = 0, subClassId = 5, flags = { cooked = true, prepared = true } },
    [13930] = { type = "Fish", itemLevel = 45, requiredLevel = 35, foodLevel = 45, classId = 0, subClassId = 5, flags = { cooked = true, prepared = true } },
    [13935] = { type = "Fish", itemLevel = 55, requiredLevel = 45, foodLevel = 55, classId = 0, subClassId = 5, flags = { cooked = true, prepared = true } },
    [5095] = { type = "Fish", itemLevel = 15, requiredLevel = 5, foodLevel = 15, classId = 0, subClassId = 5, flags = { cooked = true, prepared = true } },

    [4536] = { type = "Fruit", itemLevel = 5, requiredLevel = 4, foodLevel = 5, classId = 0, subClassId = 5, flags = { vendor = true, prepared = true } },
    [4537] = { type = "Fruit", itemLevel = 15, requiredLevel = 5, foodLevel = 15, classId = 0, subClassId = 5, flags = { vendor = true, prepared = true } },
    [4538] = { type = "Fruit", itemLevel = 25, requiredLevel = 15, foodLevel = 25, classId = 0, subClassId = 5, flags = { vendor = true, prepared = true } },
    [4539] = { type = "Fruit", itemLevel = 35, requiredLevel = 25, foodLevel = 35, classId = 0, subClassId = 5, flags = { vendor = true, prepared = true } },
    [8953] = { type = "Fruit", itemLevel = 55, requiredLevel = 45, foodLevel = 55, classId = 0, subClassId = 5, flags = { vendor = true, prepared = true } },
    [4602] = { type = "Fruit", itemLevel = 45, requiredLevel = 35, foodLevel = 45, classId = 0, subClassId = 5, flags = { vendor = true, prepared = true } },
    [29450] = { type = "Fruit", itemLevel = 75, requiredLevel = 65, foodLevel = 75, classId = 0, subClassId = 5, flags = { vendor = true, tbc = true, prepared = true } },
    [27856] = { type = "Fruit", itemLevel = 65, requiredLevel = 55, foodLevel = 65, classId = 0, subClassId = 5, flags = { vendor = true, tbc = true, prepared = true } },

    [4604] = { type = "Fungus", itemLevel = 5, requiredLevel = 4, foodLevel = 5, classId = 0, subClassId = 5, flags = { vendor = true, prepared = true } },
    [4605] = { type = "Fungus", itemLevel = 15, requiredLevel = 5, foodLevel = 15, classId = 0, subClassId = 5, flags = { vendor = true, prepared = true } },
    [4606] = { type = "Fungus", itemLevel = 25, requiredLevel = 15, foodLevel = 25, classId = 0, subClassId = 5, flags = { vendor = true, prepared = true } },
    [4607] = { type = "Fungus", itemLevel = 35, requiredLevel = 25, foodLevel = 35, classId = 0, subClassId = 5, flags = { vendor = true, prepared = true } },
    [4608] = { type = "Fungus", itemLevel = 45, requiredLevel = 35, foodLevel = 45, classId = 0, subClassId = 5, flags = { vendor = true, prepared = true } },
    [8948] = { type = "Fungus", itemLevel = 55, requiredLevel = 45, foodLevel = 55, classId = 0, subClassId = 5, flags = { vendor = true, prepared = true } },
    [27859] = { type = "Fungus", itemLevel = 65, requiredLevel = 55, foodLevel = 65, classId = 0, subClassId = 5, flags = { vendor = true, tbc = true, prepared = true } },
    [29453] = { type = "Fungus", itemLevel = 75, requiredLevel = 65, foodLevel = 75, classId = 0, subClassId = 5, flags = { vendor = true, tbc = true, prepared = true } },

    [117] = { type = "Meat", itemLevel = 5, requiredLevel = 6, foodLevel = 5, classId = 0, subClassId = 5, flags = { vendor = true, prepared = true } },
    [2287] = { type = "Meat", itemLevel = 15, requiredLevel = 5, foodLevel = 15, classId = 0, subClassId = 5, flags = { vendor = true, prepared = true } },
    [3770] = { type = "Meat", itemLevel = 25, requiredLevel = 15, foodLevel = 25, classId = 0, subClassId = 5, flags = { vendor = true, prepared = true } },
    [4599] = { type = "Meat", itemLevel = 45, requiredLevel = 35, foodLevel = 45, classId = 0, subClassId = 5, flags = { vendor = true, prepared = true } },
    [8952] = { type = "Meat", itemLevel = 55, requiredLevel = 45, foodLevel = 55, classId = 0, subClassId = 5, flags = { vendor = true, prepared = true } },
    [3771] = { type = "Meat", itemLevel = 35, requiredLevel = 25, foodLevel = 35, classId = 0, subClassId = 5, flags = { vendor = true, prepared = true } },
    [29451] = { type = "Meat", itemLevel = 75, requiredLevel = 65, foodLevel = 75, classId = 0, subClassId = 5, flags = { vendor = true, tbc = true, prepared = true } },
    [27854] = { type = "Meat", itemLevel = 65, requiredLevel = 55, foodLevel = 65, classId = 0, subClassId = 5, flags = { vendor = true, tbc = true, prepared = true } },
    [769] = { type = "Meat", itemLevel = 5, requiredLevel = 0, foodLevel = 5, classId = 7, subClassId = 8, flags = { raw = true, cookable = true, petRaw = true } },
    [12037] = { type = "Meat", itemLevel = 30, requiredLevel = 0, foodLevel = 30, classId = 7, subClassId = 8, flags = { raw = true, cookable = true, petRaw = true } },
    [12208] = { type = "Meat", itemLevel = 40, requiredLevel = 0, foodLevel = 40, classId = 7, subClassId = 8, flags = { raw = true, cookable = true, petRaw = true } },
    [12203] = { type = "Meat", itemLevel = 30, requiredLevel = 0, foodLevel = 30, classId = 7, subClassId = 8, flags = { raw = true, cookable = true, petRaw = true } },
    [12205] = { type = "Meat", itemLevel = 40, requiredLevel = 0, foodLevel = 40, classId = 7, subClassId = 8, flags = { raw = true, cookable = true, petRaw = true } },
    [12184] = { type = "Meat", itemLevel = 30, requiredLevel = 0, foodLevel = 30, classId = 7, subClassId = 8, flags = { raw = true, cookable = true, petRaw = true } },
    [3712] = { type = "Meat", itemLevel = 30, requiredLevel = 0, foodLevel = 30, classId = 7, subClassId = 8, flags = { raw = true, cookable = true, petRaw = true } },
    [12206] = { type = "Meat", itemLevel = 40, requiredLevel = 0, foodLevel = 40, classId = 7, subClassId = 8, flags = { raw = true, cookable = true, petRaw = true } },
    [12202] = { type = "Meat", itemLevel = 30, requiredLevel = 0, foodLevel = 30, classId = 7, subClassId = 8, flags = { raw = true, cookable = true, petRaw = true } },
    [3667] = { type = "Meat", itemLevel = 23, requiredLevel = 0, foodLevel = 23, classId = 7, subClassId = 8, flags = { raw = true, cookable = true, petRaw = true } },
    [2677] = { type = "Meat", itemLevel = 14, requiredLevel = 0, foodLevel = 14, classId = 7, subClassId = 8, flags = { raw = true, cookable = true, petRaw = true } },
    [12204] = { type = "Meat", itemLevel = 35, requiredLevel = 0, foodLevel = 35, classId = 7, subClassId = 8, flags = { raw = true, cookable = true, petRaw = true } },
    [3173] = { type = "Meat", itemLevel = 11, requiredLevel = 0, foodLevel = 11, classId = 7, subClassId = 8, flags = { raw = true, cookable = true, petRaw = true } },
    [2672] = { type = "Meat", itemLevel = 5, requiredLevel = 0, foodLevel = 5, classId = 7, subClassId = 8, flags = { raw = true, cookable = true, petRaw = true } },
    [3731] = { type = "Meat", itemLevel = 23, requiredLevel = 0, foodLevel = 23, classId = 7, subClassId = 8, flags = { raw = true, cookable = true, petRaw = true } },
    [1015] = { type = "Meat", itemLevel = 19, requiredLevel = 0, foodLevel = 19, classId = 7, subClassId = 8, flags = { raw = true, cookable = true, petRaw = true } },
    [3404] = { type = "Meat", itemLevel = 35, requiredLevel = 0, foodLevel = 35, classId = 7, subClassId = 8, flags = { raw = true, cookable = true, petRaw = true } },
    [2674] = { type = "Meat", itemLevel = 13, requiredLevel = 0, foodLevel = 13, classId = 7, subClassId = 8, flags = { raw = true, cookable = true, petRaw = true } },
    [729] = { type = "Meat", itemLevel = 10, requiredLevel = 0, foodLevel = 10, classId = 7, subClassId = 8, flags = { raw = true, cookable = true, petRaw = true } },
    [5465] = { type = "Meat", itemLevel = 5, requiredLevel = 0, foodLevel = 5, classId = 7, subClassId = 8, flags = { raw = true, cookable = true, petRaw = true } },
    [2673] = { type = "Meat", itemLevel = 10, requiredLevel = 0, foodLevel = 10, classId = 7, subClassId = 8, flags = { raw = true, cookable = true, petRaw = true } },
    [2924] = { type = "Meat", itemLevel = 14, requiredLevel = 0, foodLevel = 14, classId = 7, subClassId = 8, flags = { raw = true, cookable = true, petRaw = true } },
    [723] = { type = "Meat", itemLevel = 12, requiredLevel = 0, foodLevel = 12, classId = 7, subClassId = 8, flags = { raw = true, cookable = true, petRaw = true } },
    [5467] = { type = "Meat", itemLevel = 10, requiredLevel = 0, foodLevel = 10, classId = 7, subClassId = 8, flags = { raw = true, cookable = true, petRaw = true } },
    [27671] = { type = "Meat", itemLevel = 60, requiredLevel = 0, foodLevel = 60, classId = 7, subClassId = 8, flags = { raw = true, cookable = true, petRaw = true, tbc = true } },
    [27674] = { type = "Meat", itemLevel = 60, requiredLevel = 0, foodLevel = 60, classId = 7, subClassId = 8, flags = { raw = true, cookable = true, petRaw = true, tbc = true } },
    [27677] = { type = "Meat", itemLevel = 60, requiredLevel = 0, foodLevel = 60, classId = 7, subClassId = 8, flags = { raw = true, cookable = true, petRaw = true, tbc = true } },
    [27678] = { type = "Meat", itemLevel = 60, requiredLevel = 0, foodLevel = 60, classId = 7, subClassId = 8, flags = { raw = true, cookable = true, petRaw = true, tbc = true } },
    [27681] = { type = "Meat", itemLevel = 60, requiredLevel = 0, foodLevel = 60, classId = 7, subClassId = 8, flags = { raw = true, cookable = true, petRaw = true, tbc = true } },
    [27682] = { type = "Meat", itemLevel = 60, requiredLevel = 0, foodLevel = 60, classId = 7, subClassId = 8, flags = { raw = true, cookable = true, petRaw = true, tbc = true } },
    [31670] = { type = "Meat", itemLevel = 65, requiredLevel = 0, foodLevel = 65, classId = 7, subClassId = 8, flags = { raw = true, cookable = true, petRaw = true, tbc = true } },
    [31671] = { type = "Meat", itemLevel = 65, requiredLevel = 0, foodLevel = 65, classId = 7, subClassId = 8, flags = { raw = true, cookable = true, petRaw = true, tbc = true } },
    [27651] = { type = "Meat", itemLevel = 65, requiredLevel = 55, foodLevel = 65, classId = 0, subClassId = 5, flags = { tbc = true, cooked = true, prepared = true } },
    [27655] = { type = "Meat", itemLevel = 65, requiredLevel = 55, foodLevel = 65, classId = 0, subClassId = 5, flags = { tbc = true, cooked = true, prepared = true } },
    [27657] = { type = "Meat", itemLevel = 65, requiredLevel = 55, foodLevel = 65, classId = 0, subClassId = 5, flags = { tbc = true, cooked = true, prepared = true } },
    [27658] = { type = "Meat", itemLevel = 65, requiredLevel = 55, foodLevel = 65, classId = 0, subClassId = 5, flags = { tbc = true, cooked = true, prepared = true } },
    [27659] = { type = "Meat", itemLevel = 65, requiredLevel = 55, foodLevel = 65, classId = 0, subClassId = 5, flags = { tbc = true, cooked = true, prepared = true } },
    [27660] = { type = "Meat", itemLevel = 65, requiredLevel = 55, foodLevel = 65, classId = 0, subClassId = 5, flags = { tbc = true, cooked = true, prepared = true } },
    [31672] = { type = "Meat", itemLevel = 65, requiredLevel = 55, foodLevel = 65, classId = 0, subClassId = 5, flags = { tbc = true, cooked = true, prepared = true } },
    [31673] = { type = "Meat", itemLevel = 65, requiredLevel = 55, foodLevel = 65, classId = 0, subClassId = 5, flags = { tbc = true, cooked = true, prepared = true } },
    [33872] = { type = "Meat", itemLevel = 65, requiredLevel = 55, foodLevel = 65, classId = 0, subClassId = 5, flags = { tbc = true, cooked = true, prepared = true } },
    [28501] = { type = "Meat", itemLevel = 55, requiredLevel = 55, foodLevel = 55, classId = 0, subClassId = 5, flags = { tbc = true, cooked = true, prepared = true, notFeedable = true } },
    [4457] = { type = "Meat", itemLevel = 35, requiredLevel = 25, foodLevel = 35, classId = 0, subClassId = 5, flags = { cooked = true, prepared = true } },
    [3726] = { type = "Meat", itemLevel = 25, requiredLevel = 15, foodLevel = 25, classId = 0, subClassId = 5, flags = { cooked = true, prepared = true } },
    [12213] = { type = "Meat", itemLevel = 35, requiredLevel = 25, foodLevel = 35, classId = 0, subClassId = 5, flags = { cooked = true, prepared = true } },
    [2679] = { type = "Meat", itemLevel = 5, requiredLevel = 1, foodLevel = 5, classId = 0, subClassId = 5, flags = { cooked = true, prepared = true } },
    [2684] = { type = "Meat", itemLevel = 15, requiredLevel = 5, foodLevel = 15, classId = 0, subClassId = 5, flags = { cooked = true, prepared = true } },
    [2683] = { type = "Meat", itemLevel = 15, requiredLevel = 5, foodLevel = 15, classId = 0, subClassId = 5, flags = { cooked = true, prepared = true } },
    [12224] = { type = "Meat", itemLevel = 7, requiredLevel = 1, foodLevel = 7, classId = 0, subClassId = 5, flags = { cooked = true, prepared = true } },
    [3662] = { type = "Meat", itemLevel = 15, requiredLevel = 5, foodLevel = 15, classId = 0, subClassId = 5, flags = { cooked = true, prepared = true } },
    [19306] = { type = "Meat", itemLevel = 45, requiredLevel = 35, foodLevel = 45, classId = 0, subClassId = 5, flags = { cooked = true, prepared = true } },
    [19223] = { type = "Meat", itemLevel = 5, requiredLevel = 1, foodLevel = 5, classId = 0, subClassId = 5, flags = { cooked = true, prepared = true } },
    [2687] = { type = "Meat", itemLevel = 15, requiredLevel = 5, foodLevel = 15, classId = 0, subClassId = 5, flags = { cooked = true, prepared = true } },
    [20074] = { type = "Meat", itemLevel = 30, requiredLevel = 20, foodLevel = 30, classId = 0, subClassId = 5, flags = { cooked = true, prepared = true } },
    [3727] = { type = "Meat", itemLevel = 25, requiredLevel = 15, foodLevel = 25, classId = 0, subClassId = 5, flags = { cooked = true, prepared = true } },
    [13851] = { type = "Meat", itemLevel = 35, requiredLevel = 25, foodLevel = 35, classId = 0, subClassId = 5, flags = { cooked = true, prepared = true } },
    [12212] = { type = "Meat", itemLevel = 35, requiredLevel = 25, foodLevel = 35, classId = 0, subClassId = 5, flags = { cooked = true, prepared = true } },
    [12209] = { type = "Meat", itemLevel = 25, requiredLevel = 15, foodLevel = 25, classId = 0, subClassId = 5, flags = { cooked = true, prepared = true } },
    [7097] = { type = "Meat", itemLevel = 5, requiredLevel = 1, foodLevel = 5, classId = 0, subClassId = 5, flags = { cooked = true, prepared = true } },
    [19305] = { type = "Meat", itemLevel = 25, requiredLevel = 15, foodLevel = 25, classId = 0, subClassId = 5, flags = { cooked = true, prepared = true } },
    [19224] = { type = "Meat", itemLevel = 35, requiredLevel = 25, foodLevel = 35, classId = 0, subClassId = 5, flags = { cooked = true, prepared = true } },
    [12210] = { type = "Meat", itemLevel = 35, requiredLevel = 25, foodLevel = 35, classId = 0, subClassId = 5, flags = { cooked = true, prepared = true } },
    [2681] = { type = "Meat", itemLevel = 7, requiredLevel = 1, foodLevel = 7, classId = 0, subClassId = 5, flags = { cooked = true, prepared = true } },
    [5473] = { type = "Meat", itemLevel = 8, requiredLevel = 1, foodLevel = 8, classId = 0, subClassId = 5, flags = { cooked = true, prepared = true } },
    [6890] = { type = "Meat", itemLevel = 15, requiredLevel = 5, foodLevel = 15, classId = 0, subClassId = 5, flags = { cooked = true, prepared = true } },
    [3729] = { type = "Meat", itemLevel = 35, requiredLevel = 25, foodLevel = 35, classId = 0, subClassId = 5, flags = { cooked = true, prepared = true } },
    [19304] = { type = "Meat", itemLevel = 15, requiredLevel = 5, foodLevel = 15, classId = 0, subClassId = 5, flags = { cooked = true, prepared = true } },
    [3728] = { type = "Meat", itemLevel = 30, requiredLevel = 20, foodLevel = 30, classId = 0, subClassId = 5, flags = { cooked = true, prepared = true } },
  },

  nameHints = {
    Meat = { "meat", "jerky", "ribs", "steak", "chop", "ham", "venison", "hot dog", "omelet", "肉", "肋", "火腿", "热狗", "熱狗", "煎蛋卷", "秃鹫", "禿鷲", "掠食者" },
    Fish = { "fish", "trout", "salmon", "snapper", "cod", "catfish", "mackerel", "halibut", "鱼", "魚", "鲑", "鮭", "鳕", "鱈", "鲶", "鯰", "鳟", "鱒" },
    Fruit = { "fruit", "apple", "banana", "watermelon", "pumpkin", "grape", "berries", "水果", "苹果", "蘋果", "香蕉", "西瓜", "南瓜", "葡萄", "莓" },
    Bread = { "bread", "muffin", "roll", "croissant", "bagel", "pie", "面包", "麵包", "松饼", "鬆餅", "甜面包", "牛角面包", "馅饼", "餡餅" },
    Fungus = { "fungus", "mushroom", "truffle", "蘑菇", "菌", "松露" },
    Cheese = { "cheese", "sharp", "brie", "swiss", "奶酪", "乳酪", "起司", "干酪", "乾酪" },
  },
}
